name:  Python CI

on:
  - push

jobs:
  run-linters:
    name: Run linter and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
           pip install poetry
           poetry update
           make install
      - name: Run tests
        env:
          SECRET_KEY: 'django-insecure-b&xn*jnt_l=$so!dz*^8^_r@0dlcj-@c@x*%jeigj&%k$@=!91'
          ROLLBAR_KEY: 'rollbar_key'
          DEBUG: True
        run: |
           make test
      - name: code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 'SOME_KEY'
          SECRET_KEY: 'django-insecure-b&xn*jnt_l=$so!dz*^8^_r@0dlcj-@c@x*%jeigj&%k$@=!91'
          ROLLBAR_KEY: 'rollbar_key'
        with:
          coverageCommand: make test-coverage
          debug: true
      - name: Run linter
        run: |
           make lint
